---
title: "HOMEWORK 9"
author: "Sean  Carey"
date: "11/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tree)
library(randomForest)
library(gbm)

```

## 1.

```{r 1.}

#read in data
AMZ <- read_csv("https://www.openml.org/data/get_csv/1681098/phpmPOD5A")
#set "Target" as factor
AMZ$target <- as.factor(AMZ$target)

#split AMZ into training and test data sets

train <- sample(1:nrow(AMZ), size = nrow(AMZ)*0.8)
test <- dplyr::setdiff(1:nrow(AMZ), train)

AMZ_training <-  AMZ[train, ]
AMZ_test <- AMZ[test, ]



```
##2. 

```{r train class model}

#Fit Regression Tree 

tree_fit_1 <- tree(target ~ ., data = AMZ_training)
#Tree only has one node!!!



```
```{r train bagged Tree Model}

#use bagging for tree model

bag_fit_1 <- randomForest(target ~ ., data = AMZ_training, mtry = ncol(AMZ_training)-1, ntree = 200, importance=TRUE )

bag_fit_1

```
```{r Rand Forest Fit}

rf_fit_1 <- randomForest(target ~ ., data = AMZ_training, mtry = (ncol(AMZ_training)-1)/3, ntree = 500, importance=TRUE )

rf_fit_1

```

```{r boosted fit}

boost_fit_1 <- gbm(target ~ ., data = AMZ_training, distribution = "bernoulli", n.trees = 5000, 
                                shrinkage = 0.1, interaction.depth = 4)

boost_fit_1

```

